### ISSUE TITLE
Crash if <description/> tag is present but empty

### ISSUE THREAD

**Issue by ssssam** [Wilm0r/giggity#16]
Hello

I've been seeing an issue when trying to parse the GUADEC 2017 and 2016 schedule with Giggity. The schedule was failing to load with a NullPointerException. Here's the full log from `adb logcat`:

```
07-04 17:09:53.453 E/Schedule.loadXml( 5500): XML parse exception: java.lang.NullPointerException
07-04 17:09:53.453 W/System.err( 5500): java.lang.NullPointerException
07-04 17:09:53.463 W/System.err( 5500):         at net.gaast.giggity.Giggity.fuzzyStarsWith(Giggity.java:191)
07-04 17:09:53.463 W/System.err( 5500):         at net.gaast.giggity.Schedule$PentabarfParser.endElement(Schedule.java:1018)
07-04 17:09:53.463 W/System.err( 5500):         at org.apache.harmony.xml.ExpatParser.endElement(ExpatParser.java:156)
07-04 17:09:53.463 W/System.err( 5500):         at org.apache.harmony.xml.ExpatParser.appendChars(Native Method)
07-04 17:09:53.463 W/System.err( 5500):         at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:497)
07-04 17:09:53.463 W/System.err( 5500):         at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:484)
07-04 17:09:53.463 W/System.err( 5500):         at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:309)
07-04 17:09:53.463 W/System.err( 5500):         at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:267)
07-04 17:09:53.463 W/System.err( 5500):         at android.util.Xml.parse(Xml.java:71)
07-04 17:09:53.463 W/System.err( 5500):         at net.gaast.giggity.Schedule.loadXml(Schedule.java:362)
07-04 17:09:53.463 W/System.err( 5500):         at net.gaast.giggity.Schedule.loadPentabarf(Schedule.java:357)
07-04 17:09:53.463 W/System.err( 5500):         at net.gaast.giggity.Schedule.loadSchedule(Schedule.java:306)
07-04 17:09:53.463 W/System.err( 5500):         at net.gaast.giggity.Giggity.getSchedule(Giggity.java:116)
07-04 17:09:53.463 W/System.err( 5500):         at net.gaast.giggity.ScheduleViewActivity$6.run(ScheduleViewActivity.java:339)
07-04 17:09:53.463 W/System.err( 5500): XML parsing problem: java.lang.NullPointerException
07-04 17:09:53.463 W/System.err( 5500):         at net.gaast.giggity.Schedule.loadXml(Schedule.java:367)
07-04 17:09:53.463 W/System.err( 5500):         at net.gaast.giggity.Schedule.loadPentabarf(Schedule.java:357)
07-04 17:09:53.463 W/System.err( 5500):         at net.gaast.giggity.Schedule.loadSchedule(Schedule.java:306)
07-04 17:09:53.463 W/System.err( 5500):         at net.gaast.giggity.Giggity.getSchedule(Giggity.java:116)
07-04 17:09:53.463 W/System.err( 5500):         at net.gaast.giggity.ScheduleViewActivity$6.run(ScheduleViewActivity.java:339)
```

The problem seems to be an assumption that the \<description\> tag exists and contains text, here: https://github.com/Wilm0r/giggity/blob/master/app/src/main/java/net/gaast/giggity/Schedule.java#L1018

I think I can work around the issue by avoiding \<abstract\> and just providing \<description\>, but it would be good to avoid the error. You can reproduce the problem by loading the GUADEC 2016 schedule in Giggity.

**Comment by Wilm0r** [comment]
Thanks for the report! Fixed in https://github.com/Wilm0r/giggity/commit/9ab760b3838b658e3769937d1d3ef5e71d6fa18f

(And thanks for working around it, saves me from rushing a new release.)
